### ISSUE TITLE
Export data in .TCX Format

### ISSUE THREAD

**Issue by Joern-R** [cgiesche/ebikeconnect-gui#19]
In order to allow the data being imported by other software (e.g. GoldenCheetah), a common data format for export should be supported. A human readable and relatively easy to implement format is TCX - which is a XML based format defined by Garmin and widely adopted as import format from multiple software und training website providers.

I have attached a short example with only 3 trackpoints. Data per Trackpoint is:
- Position
- Altitude
- HeartrateBPM
- Cadence
- Watts

TCX XML Structure uses the following 2 Schema Definitions
 -- main schema http://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd
 -- extension schema http://www8.garmin.com/xmlschemas/ActivityExtensionv2.xsd

[TCX-Example-Short.zip](https://github.com/cgiesche/ebikeconnect-gui/files/299271/TCX-Example-Short.zip)

BR
Joern

**Comment by cgiesche** [comment]
Ein erster Wurf ist fertig. Die Werte sehen soweit einigermaßen realistisch aus. GoldenCheetah beschwert sich zumindest schon mal nicht.

Beispiel-Export:
[sample_tcx_export.zip](https://github.com/cgiesche/ebikeconnect-gui/files/465918/sample_tcx_export.zip)
