### ISSUE TITLE
Missing build dependencies

### ISSUE THREAD

**Issue by michaelprager** [cgiesche/ebikeconnect-gui#23]
The project fails to compile for me to due missing dependencies de.perdoctus.gpx and de.perdoctus.tcx. The message is the following:

> [ERROR] /tmp/build/ebikeconnect-gui/src/main/java/de/perdoctus/ebikeconnect/gui/services/export/GpxExportService.java:[34,1] package de.perdoctus.gpx does not exist
> [ERROR] /tmp/build/ebikeconnect-gui/src/main/java/de/perdoctus/ebikeconnect/gui/services/export/TcxExportService.java:[33,1] package de.perdoctus.tcx does not exist
> [ERROR] /tmp/build/ebikeconnect-gui/src/main/java/de/perdoctus/ebikeconnect/gui/services/export/TcxExportService.java:[34,34] package de.perdoctus.tcx.extension does not exist
> [ERROR] /tmp/build/ebikeconnect-gui/src/main/java/de/perdoctus/ebikeconnect/gui/services/export/TcxExportService.java:[35,34] package de.perdoctus.tcx.extension does not exist
> [ERROR] /tmp/build/ebikeconnect-gui/src/main/java/de/perdoctus/ebikeconnect/gui/services/export/GpxExportService.java:[56,26]

Looks like these two projects are not available anywhere.

Also, I've noticed that for my build setup (archlinux), I need to add a couple of additional dependencies to the pom.xml in order to get this to work (apart from the missing packages above of course). I've attached a patch for those.

[0001-added-missing-dependencies-to-pom.xml.zip](https://github.com/cgiesche/ebikeconnect-gui/files/1168140/0001-added-missing-dependencies-to-pom.xml.zip)

Since there were no build instructions to be found, here is the list of commands I used:

```
# archlinux build environment setup
pacman -S jdk8-openjdk maven java-openjfx

cd /tmp/build
git clone https://github.com/cgiesche/ebikeconnect-gui.git
git clone https://github.com/cgiesche/ebikeconnect-api.git
git clone https://github.com/cgiesche/javafx-cdi-bootstrap.git

cd javafx-cdi-bootstrap
mvn install

cd ../ebikeconnect-api
mvn install

cd ../ebikeconnect-gui
mvn package -P build-fatjar

# if everything went okay, this will run the build
java -jar target/jfx/app/ebikeconnect-gui-0.5-SNAPSHOT-jfx.jar
```

**Comment by cgiesche** [comment]
Hey @michaelprager,

everything you did (except adding dependencies) sounds good and should work. Those dependencies are (or at least should be) resolved transiently by maven.

The packages `de.perdoctus.gpx` and `de.perdoctus.tcx` are normally generated during the build of the gui project (from xsd-files).

I just checked out the current master branches as you did and tried to build the project with your commands - with success.

Both problems could be caused by maven (which is responsible for resolving transient dependencies and executing the code generation plugin during the build). Which version of maven are you using? I just tried 3.3.9 and 3.5.0.

**Comment by cgiesche** [comment]
Just to be sure: I always use `mvn clean install` to be sure everything is rebuild. But this should not make a difference in this case.

**Comment by michaelprager** [comment]
You're right, the build actually works when build correctly :-)

My mistake was to run `mvn package` without specifying the profile first. That in turn causes 
`mvn package -P build-fatjar` to fail. Because in that case it skips the generation:

> [INFO] --- jaxb2-maven-plugin:2.2:xjc (gpx-schema) @ ebikeconnect-gui ---
> [INFO] No changes detected in schema or binding files - skipping JAXB generation.

Anyways this now compiles fine for me, thanks for the heads up!
