### ISSUE TITLE
Not building on mac

### ISSUE THREAD

**Issue by mrommel** [cgiesche/ebikeconnect-gui#7]
Please remove the / before 
{code}
                                <source>/src/main/xsd/gpx.xsd</source>
                                <source>/src/main/xsd/TrackPointExtensionv1.xsd</source>
{code}
and
{code}
                                <xjbSource>/src/main/bindings</xjbSource>
{code}
in the pom.xml

**Comment by cgiesche** [comment]
I will take a look as soon as I am at home.
(As you may have noticed, you need to build https://github.com/cgiesche/ebikeconnect-api before 'ebikeconnect-gui' as it is not (yet) available via maven central.)
